### ISSUE TITLE
homeassistant

### ISSUE THREAD

**Issue by huaxiuyiwei** [IceWhaleTech/CasaOS#150] opened 2022-04-07 14:27 UTC
**Describe the bug**

在面板上设置一下homeassistant的特权选项，镜像就被重置了，之前设置的信息都没有了。而且没有任何提示。

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.2.10
	 - Disk Total: 29676 
	 - Disk Used: 3523 
	 - Sync State: Sync img: true
	linuxserver/syncthing,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:1849M Core:4 Linux home 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux]
	 - Browser: Edge 
	 - Version: 97.0.1072.62

**Comment by LinkLeong** [comment] 2022-04-26 03:19
这个问题我们已经查到原因,后面更新后我们会重新给回复,感谢反馈.

**Comment by LinkLeong** [comment] 2022-06-01 02:54
Hello, my previous guess is a mirroring problem, but after many checks did not appear the problem you said, you said the problem is vital to us, so I hope you provide screenshots to tell us the screenshots thrown out of the content, you can also add my WeChat: guanningchuan, we communicate in Chinese in WeChat.
你好,我之前的猜想是镜像问题,但是经过多次排查并未出现你说的问题,你说的问题对我们至关重要,所以希望你提供截图告知我们截图丢出内容,你还可以加我微信：guanningchuan，我们在微信里用中文交流。

**Comment by LinkLeong** [comment] 2022-06-06 01:58
We will close the issue, if you have any further questions, please resubmit the issue. Thank you for your feedback!

**Closed by LinkLeong** 2022-06-06 01:58 UTC
Labels: question
