### ISSUE TITLE
Cannot load the appstore

### ISSUE THREAD

**Issue by Felix-Pedro** [IceWhaleTech/CasaOS#315] opened 2022-06-21 00:16 UTC
**Describe the bug**

Hi I'm not able to load the appstore at all

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 71633 
	 - Disk Used: 4959 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [CentOS Stream release 9 Bit:64 Mem:3614M Core:4 Linux jyn 5.14.0-109.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 10 09:54:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 101.0.0.0

**Comment by JohnGuan** [comment] 2022-06-21 00:49
Duplicate of #302

**Closed** 2022-06-21 00:49 UTC
Labels: duplicate
