### ISSUE TITLE
[Bug] No Secure Websocket behind reverse proxy

### ISSUE THREAD

**Issue by Triskae** [IceWhaleTech/CasaOS#683] opened 2022-11-17 09:23 UTC
**Describe the bug**
I installed casasOS, everythings works very well, to access my instance I put casaOS behind a reverse proxy (Nginx Reverse proxy). All the https traffic works well except for the websocket traffic (used for terminal and live data about the processor, temps, load etc). So when use my domain to connect to casaOS, I don't have the terminal nor the live data about the host machine. 

**To Reproduce**
1. Create casaOS instance
2. Put it behind proxy (configure a proxy pass like in the screenshot provided below)
3. Access casaOS with the domain name with HTTPS, not the ip
4. Try to open the console, or open the devtools in  the browser, you will see the error.

**Expected behavior**
The excepted behavior is that casaOS should support secure websocket  (WSS) instead of supporting only unsecure websocket.

**Screenshots**

![image](https://user-images.githubusercontent.com/28785555/202406074-49d2175b-d2c7-43f1-abe8-ed1d3a9ba340.png)

I need to refresh the page to refresh the data above
![image](https://user-images.githubusercontent.com/28785555/202406150-965baa26-4c1d-4d5a-81c6-841cc6c353d0.png)

![image](https://user-images.githubusercontent.com/28785555/202406307-15b0a4c2-4e98-412f-9243-377eeb61dc01.png)

![image](https://user-images.githubusercontent.com/28785555/202406414-5e1278c9-5138-48e1-b068-8e813cd7430e.png)

![image](https://user-images.githubusercontent.com/28785555/202407535-e21160f6-c9cf-4218-ad25-019a63066ed1.png)

![image](https://user-images.githubusercontent.com/28785555/202407587-86bdaf59-cf2b-49db-92d6-bff2e851a585.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu (host)
 - Browser Chromium and Firefox
 - Version 105.0.5195.125

**Logs**

NA

**Additional context**
NA

**Comment by Triskae** [comment] 2022-11-21 13:33
Great, thanks a lot !

**Comment by Triskae** [comment] 2022-11-23 12:31
The console seems to work now, but the live data about the memory usage etc seems to not work :/ Maybe a miss configuration of my port forwarding

**Comment by zhanghengxin** [comment] 2022-11-24 02:50
If your current system version is 0.3.8, then the socket should be fine. I look forward to your latest feedback.

**Comment by Triskae** [comment] 2022-11-25 11:00
Yep I have the 0.3.8  version, everything works as expected, except for the live data (RAM usage, CPU temp etc), it's stuck a 0W and the last value retrieved during first loading.

**Comment by zhanghengxin** [comment] 2022-11-25 11:09
because it‘s perennially at 0.9
![image](https://user-images.githubusercontent.com/24197448/203972219-a0fe847a-5978-4154-b298-fbe6ceb7b1cb.png)

**Comment by Triskae** [comment] 2022-11-25 11:13
I don't understand.
When I use the internal IP like you, I have no problem, the CPU usage, temp and RAM usage update every second, BUT, When I access to CasaOS through nginx, those values stop refreshing

**Comment by zhanghengxin** [comment] 2022-11-27 15:15
> I don't understand. When I use the internal IP like you, I have no problem, the CPU usage, temp and RAM usage update every second, BUT, When I access to CasaOS through nginx, those values stop refreshing

Maybe you need to do it.  
> https://www.nginx.com/blog/websocket-nginx/

**Comment by Triskae** [comment] 2022-11-27 15:23
I already have a reverse proxy, and it's not working as I was saying 
Behind a reverse proxy, it's not working, the WebSocket won't work when I use reverse proxy

**Comment by zhanghengxin** [comment] 2022-11-30 05:52
@raller1028

**Comment by zhanghengxin** [comment] 2022-12-01 11:17
I need to make sure that you have updated to 0.3.8 and that you can access it properly using ip with https.
then, Are there still errors reported when you access it by NGINX about “WebSocket” or “WS”

**Comment by Triskae** [comment] 2022-12-01 11:46
I have indeed the 0.3.8 version, as you can see in the screenshot above: 
![image](https://user-images.githubusercontent.com/28785555/205044214-7965c768-935c-465b-a4ce-2c27d907ae50.png)

https using ip, doesn't work, is any self signed certificated shipped with CasaOS ?
![image](https://user-images.githubusercontent.com/28785555/205044444-18b1f85d-cca8-46bd-abce-77b818745548.png)

When I try to access casaOS with my domain name (and NOT with my IP), I have indeed an error about WS, as you can see in my screenshot above: 

![image](https://user-images.githubusercontent.com/28785555/205044793-87048682-c29f-4538-94a5-9234480c6f81.png)

**Comment by zhanghengxin** [comment] 2022-12-01 12:18
Am I now to understand that the WebSocket issue I fixed in 0.3.8 that did not support TLS was not fixed.
Am I now to understand that the WebSocket issue I fixed in 0.3.8 with no support for TLS is not fixed. Instead, my previous understanding was that this was a new issue caused by NGINX.

**Closed** 2023-02-01 09:54 UTC
Labels: bug

**Comment by tigerinus** [comment] 2023-02-02 01:07
@Triskae - can you try this again in v0.4.1?

**Comment by Triskae** [comment] 2023-02-02 19:09
Still have the issue ... 
CasaOS is behind a Nginx Reverse Proxy, do you know if I have a specific config to make it work ?
I don't have any problem with Home Assistant for exemple, same configuration, behind Nginx, and there's also WS, and no issues ...

**Comment by tigerinus** [comment] 2023-02-02 20:47
Are you unable to get WSS (WebSocket Secured) work, or neither of WSS and HTTPS?

In last release we moved websocket endpoint from its dedicated port to the same port as HTTP. So in theory, if you are able to access CasaOS via HTTPS (using Nginx), then you should also have access to WSS.

**Comment by Triskae** [comment] 2023-02-02 20:57
I'm sorry, I din't waited long enough, I take a little bit of time to update, but it's working like a charm !! No errors in the console ! Thanks !!
