### ISSUE TITLE
点击应用中心报错

### ISSUE THREAD

**Issue by bystart** [IceWhaleTech/CasaOS#332] opened 2022-06-29 14:51 UTC
**Describe the bug**

点击应用中心无法正常加载列表，web控制台js报错
报错内容：
vue.esm.js:629 [Vue warn]: Error in created hook: "TypeError: Cannot read properties of undefined (reading 'length')"

found in

---> <AppPanel> at src/components/Apps/AppPanel.vue
       <BModal>
         <AppSection> at src/components/Apps/AppSection.vue
           <HomePage> at src/views/Home.vue
             <App> at src/App.vue
               <Root>
vue.esm.js:1905 TypeError: Cannot read properties of undefined (reading 'length')

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.2.1
	 - Disk Total: 18418 
	 - Disk Used: 2082 
	 - Sync State: Sync img: false
	Sync Key length: 0
	 - System Info: [CentOS Linux release 7.9.2009 (Core) Bit:64 Mem:1837M Core:2 Linux CasaOS 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux]
	 - Browser: Chrome 
	 - Version: 103.0.0.0

**Comment by JohnGuan** [comment] 2022-06-29 16:40
Duplicate of #269 
这是一个已知问题，感谢你的支持！你可以加我的微信guanningchuan，我们可以在微信中使用中文进行交流！

**Closed by JohnGuan** 2022-06-29 16:40 UTC
Labels: duplicate
