### ISSUE TITLE
[Feedback] Spindown HDD

### ISSUE THREAD

**Issue by jeremyit** [IceWhaleTech/CasaOS#853] opened 2023-01-31 21:55 UTC
### Description

I've worked on standby HDD with zimaboard and Casaos.
HDPARM doesn't  work.
hd-idle work like a charm but ! only if CasaOS services are down. I've did multiple try, I think that is caused by Casaos storage management or smartctl called by Casaos for smart check.

**Comment by jeremyit** [comment] 2023-02-02 21:17
Finally not Casaos but hd-idle issue

**Comment by ETWang1991** [comment] 2023-02-09 01:23
We have found the cause of this problem and estimate that it will be solved in version 0.4.3

**Comment by jeremyit** [comment] 2023-02-18 18:00
I found the root cause is udisks2 
If this service down then spindown works

**Comment by LinkLeong** [comment] 2023-02-24 03:10
Thank you for your feedback, we also found the problem, but at the moment we can't remove the dependency of udisks2, do you have any better suggestion?

**Comment by LinkLeong** [comment] 2023-03-01 06:01
We will close the issue and reopen it if you have any questions.

**Closed by LinkLeong** 2023-03-01 06:01 UTC
Labels: feedback
