### ISSUE TITLE
[Bug] "can't open '/proc/net/tcp6'"

### ISSUE THREAD

**Issue by rodhammond** [IceWhaleTech/CasaOS#1332] opened 2023-08-09 12:49 UTC
Build: Latest

Situation: Installing new app container via store or "import" yaml file.
Error: "can't open '/proc/net/tcp6'"

Issue: I have deliberately disabled IP6 on my raspberry pi because it is only exposed to internal LAN. However, CasaOS requires IP6 to be enabled when installing apps. I've noticed if using a "docker run ..." command there is no error.

Solution: Remove IP6 CaSaOS requirements.

**Comment by CorrectRoadH** [comment] 2023-08-10 06:42
I can't reproduce it.🤔 I think it may be caused by your app container. Would you share your app yaml to help us to fix the problem?

**Comment by rodhammond** [comment] 2023-08-10 12:33
This happens when I add "ipv6.disable=1" to the raspberry pi config file "/boot/cmdline.txt".

That apparently, prevents "/proc/net/tcp6" from being created. Your app store containers somehow need it, but a regular "docker run" command doesn't.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CorrectRoadH** [comment] 2023-08-24 09:35
Yes. I can reproduce it on my RaspberryPi. It seems to be a specify problem that only belongs to RaspberryPi.  We will try to fix it.

**Comment by yanxunhu** [comment] 2023-08-28 04:50
same error on ubuntu 22.04 with ipv6 disabled in grub

**Comment by DarthArk** [comment] 2023-09-09 19:30
> same error on ubuntu 22.04 with ipv6 disabled in grub

Same error on the same 22.04 ubuntu build. Enabling or disabling ipv6 is not resolving.  All of my containers are dead in the water after updating to CasaOS v0.4.4.2

**Comment by jayvzh** [comment] 2023-11-03 01:00
Same error on ubuntu 23.04 (PVE lxc container) with ipv6 disabled from kernel. All applications cannot be installed Prompts can't open '/proc/net/tcp6'
Is it possible to not force checking ipv6?

**Closed** 2023-11-06 07:24 UTC
Labels: bug

**Comment by CorrectRoadH** [comment] 2023-11-06 08:12
Thank you all for your feedback. This bug has been fixed. You can wait for the next release🥳

**Comment by treysis** [comment] 2024-05-02 07:02
Just don't disable IPv6. It doesn't make sense.

**Comment by rodhammond** [comment] 2024-05-02 16:08
Pretty sure that's my decision to enabled or disable on my internal network. I assume your response means there is no fix.

**Comment by treysis** [comment] 2024-05-02 18:54
@rodhammond if you disable IPv6 in 2024 expect things to break. It shouldn't be disabled. If you disable it internally, it means you also can't use it externally.
