### ISSUE TITLE
[Bug] Deleting a shared folder makes the folder still visible through the File Explorer.

### ISSUE THREAD

**Issue by viktorilievski** [IceWhaleTech/CasaOS#1667] opened 2024-01-29 21:25 UTC
**Describe the bug**

> Deleting a shared folder **inside another shared folder** still appears in the File Explorer (Network Mapped Drive) and in the Shared section on the Web Interface.

**To Reproduce**

> Steps to reproduce the behavior:

1. Go to Files on CasaOS
2. Create a folder
3. Share the folder
4. Delete it
5. It's still visible in the Shared section and the File Explorer

**Expected behavior**

> It should be deleted from the Shared section therefore making it not visible in the File Explorer

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: Windows 10 x64
 - Browser Chrome
 - Version 120.0.6099.225 (Official Build) (64-bit)
```

**System Time**

> Run `timedatectl` and share the output

```
timedatectl
Local time: Mon 2024-01-29 21:13:47 UTC
Universal time: Mon 2024-01-29 21:13:47 UTC
RTC time: Mon 2024-01-29 21:13:48
Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: yes
NTP service: active
RTC in local TZ: no
```

**Logs**

> Run following command to collect corresponding logs:

**Nothing in the logs, I checked...**

**Comment by LinkLeong** [comment] 2024-02-20 10:20
I can't reproduce your problem, can you record or take a screenshot?

**Comment by raller1028** [comment] 2024-02-20 10:36
https://github.com/IceWhaleTech/CasaOS/assets/57336867/235d1a76-1ab2-44e1-b2b8-c40e578ec0b5

@viktorilievski Can you help us to check if our reproduction operation is the same as you said, we didn't reproduce the problem you said.

**Comment by LinkLeong** [comment] 2024-03-12 07:07
We will close this issue and reopen it if you have any questions.

**Closed by LinkLeong** 2024-03-12 07:07 UTC
Labels: bug
