### ISSUE TITLE
[Bug] appstore not loading

### ISSUE THREAD

**Issue by nooblolerxd** [IceWhaleTech/CasaOS#1659] opened 2024-01-26 19:08 UTC
**Describe the bug**

> app store not loading, i open the app but it aint loading

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: ubuntu server 
 - Browser firefox,safari
 - Version 22.04.01
```

**System Time**

> Run `timedatectl` and share the output

(also i tried the wiki help)

```
http://sprunge.us/rKcHB6

```

**Logs**

**Comment by koahar84** [comment] 2024-01-26 19:56
I get the same probleme. I try to uninstall casaos and re-install but the bug still persists.

**Comment by abrugsch** [comment] 2024-01-26 20:40
Forcing an update seems to fix it (even if already on latest). I had the same issue and even a fresh install of Debian 12 and CasaOS 0.4.6 exhibits it, but forcing an update (get.casaos.io/update) seems to resolve it

**Comment by idistack** [comment] 2024-01-26 20:57
@abrugsch thanks, forcing update fix the issue
`curl -fsSL https://get.casaos.io/update | sudo bash`

**Comment by NekoRomain** [comment] 2024-01-26 21:16
I have the same issue with a fresh install on a Debian 12. The problem seems to be in the function filteredPageList () (more precisely, in the pageList object)  because I got a NaN value which broke the Vue app.
![image](https://github.com/IceWhaleTech/CasaOS/assets/23728187/6f77e3d4-280f-4594-bdff-adc850e72956)

I've add a console.log and I find an NaN 
![image](https://github.com/IceWhaleTech/CasaOS/assets/23728187/473d5477-23c1-4f44-b536-367ad9d2ac99)
![image](https://github.com/IceWhaleTech/CasaOS/assets/23728187/6cc2056d-2eb4-4fc8-a0da-6d224c748790)

I hope this can help to find the root of the problem

**Comment by nooblolerxd** [comment] 2024-01-26 21:16
omg thank you so muchh!!

**Comment by abrugsch** [comment] 2024-01-26 21:34
Good work @NekoRomain hopefully that's enough to get the root problem sorted as the "fix" seems to be a band-aid for it rather than a solution

**Comment by abrugsch** [comment] 2024-01-26 21:35
Dupe of #1657

**Comment by dragonfire1119** [comment] 2024-01-26 21:39
https://github.com/IceWhaleTech/CasaOS-AppStore/pull/374#issuecomment-1912721833

**Comment by riccardobellitto** [comment] 2024-01-26 23:30
The app store is still not working: constantly loading.
I've tried forcing an update via command line but still broke.

![image](https://github.com/IceWhaleTech/CasaOS/assets/82087868/1f484810-04bf-4f7d-b7fc-89ff79fc3766)


```
riccardobellitto@sector5:~$ timedatectl
               Local time: Sat 2024-01-27 00:25:45 CET
           Universal time: Fri 2024-01-26 23:25:45 UTC
                 RTC time: Fri 2024-01-26 23:25:45
                Time zone: Europe/Rome (CET, +0100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```



```
riccardobellitto@sector5:~$ bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/casaos-healthcheck/run.sh)"
The local IP address is: 192.168.178.37
The port number is: 555
You can access it in the browser at: http://192.168.178.37:555
The port 555 is not blocked by UFW.
Service casaos-app-management.service is running.
Service casaos-gateway.service is running.
Invalid unit name "●" escaped as "\xe2\x97\x8f" (maybe you should use systemd-escape?).
WARNING: Service ● is NOT running!
Service casaos-local-storage.service is running.
Service casaos-message-bus.service is running.
Service casaos-user-service.service is running.
Service casaos.service is running.
Errors in casaos-app-management.service logs:
Jan 27 00:25:47 sector5 casaos-app-management[10472]: 2024-01-27T00:25:47.177+0100        error        error while getting appstore compose app        {"error": "lstat /var/lib/casaos/appstore/7c98580ba862e556368981f3cd3afa87: no such file or directory", "func": "service.(*AppStoreManagement).ComposeApp", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/appstore_management.go", "line": 381}
Jan 27 00:25:47 sector5 casaos-app-management[10472]: {"time":"2024-01-27T00:25:47.187258713+01:00","id":"","remote_ip":"192.168.178.21","host":"192.168.178.37:555","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","status":200,"error":"","latency":37248873,"latency_human":"37.248873ms","bytes_in":0,"bytes_out":761}
Jan 27 00:25:52 sector5 casaos-app-management[10472]: {"time":"2024-01-27T00:25:52.180089562+01:00","id":"","remote_ip":"192.168.178.21","host":"192.168.178.37:555","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","status":200,"error":"","latency":33043144,"latency_human":"33.043144ms","bytes_in":0,"bytes_out":818}
Jan 27 00:25:57 sector5 casaos-app-management[10472]: 2024-01-27T00:25:57.169+0100        error        error while getting appstore compose app        {"error": "lstat /var/lib/casaos/appstore/7c98580ba862e556368981f3cd3afa87: no such file or directory", "func": "service.(*AppStoreManagement).ComposeApp", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/appstore_management.go", "line": 381}
Jan 27 00:25:57 sector5 casaos-app-management[10472]: {"time":"2024-01-27T00:25:57.178768903+01:00","id":"","remote_ip":"192.168.178.21","host":"192.168.178.37:555","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","status":200,"error":"","latency":33736760,"latency_human":"33.73676ms","bytes_in":0,"bytes_out":818}
-----
Invalid unit name "●" escaped as "\xe2\x97\x8f" (maybe you should use systemd-escape?).
Errors in casaos-local-storage.service logs:
Jan 27 00:24:04 sector5 casaos-local-storage[10421]: 2024-01-27T00:24:04.659+0100        error        failed to publish event to message bus        {"status": "404 Not Found", "responseError": "json: unsupported type: func() (io.ReadCloser, error)", "func": "service.(*notifyServer).SendNotify", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/notify.go", "line": 32}
Jan 27 00:24:36 sector5 casaos-local-storage[10421]: 2024-01-27T00:24:36.451+0100        error        failed to publish event to message bus        {"status": "404 Not Found", "responseError": "json: unsupported type: func() (io.ReadCloser, error)", "func": "service.(*notifyServer).SendNotify", "file": "/home/runner/work/CasaOS-LocalStorage/CasaOS-LocalStorage/service/notify.go", "line": 32}
-----
Errors in casaos-message-bus.service logs:
Jan 27 00:25:15 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:15.024206422+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":647171,"latency_human":"647.171µs","bytes_in":822,"bytes_out":979}
Jan 27 00:25:20 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:20.02470717+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":653022,"latency_human":"653.022µs","bytes_in":822,"bytes_out":979}
Jan 27 00:25:25 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:25.024581239+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":619781,"latency_human":"619.781µs","bytes_in":822,"bytes_out":979}
Jan 27 00:25:30 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:30.025260859+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":677856,"latency_human":"677.856µs","bytes_in":822,"bytes_out":979}
Jan 27 00:25:35 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:35.025126319+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":672412,"latency_human":"672.412µs","bytes_in":824,"bytes_out":981}
Jan 27 00:25:40 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:40.024499138+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":739856,"latency_human":"739.856µs","bytes_in":822,"bytes_out":979}
Jan 27 00:25:45 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:45.025008828+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":650578,"latency_human":"650.578µs","bytes_in":822,"bytes_out":979}
Jan 27 00:25:50 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:50.024709544+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":670208,"latency_human":"670.208µs","bytes_in":820,"bytes_out":977}
Jan 27 00:25:55 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:25:55.02520648+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":662300,"latency_human":"662.3µs","bytes_in":822,"bytes_out":979}
Jan 27 00:26:00 sector5 casaos-message-bus[10386]: {"time":"2024-01-27T00:26:00.024983926+01:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:46489","method":"POST","uri":"/v2/message_bus/event/casaos/casaos:system:utilization","user_agent":"Go-http-client/1.1","status":200,"error":"","latency":632004,"latency_human":"632.004µs","bytes_in":822,"bytes_out":979}
-----
Service Logs: Errors Found
Some casaos services are not running. Please check the above output.
```

Here's the log of casaos-app-management:

```
riccardobellitto@sector5:~$ journalctl -xeu casaos-app-management --no-pager
...
Jan 27 00:28:27 sector5 casaos-app-management[10472]: 2024-01-27T00:28:27.170+0100        info        main app image tag is latest, thus no update available        {"image": "homebridge/homebridge:latest", "func": "service.(*ComposeApp).IsUpdateAvailableWith", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/compose_app.go", "line": 206}

Jan 27 00:28:27 sector5 casaos-app-management[10472]: {"time":"2024-01-27T00:28:27.180046738+01:00","id":"","remote_ip":"192.168.178.21","host":"192.168.178.37:555","method":"GET","uri":"/v2/app_management/web/appgrid","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0","status":200,"error":"","latency":33127062,"latency_human":"33.127062ms","bytes_in":0,"bytes_out":761}
```

**Comment by riccardobellitto** [comment] 2024-01-26 23:33
I've also tried fixing the appstore with this script:

https://github.com/bigbeartechworld/big-bear-scripts/tree/master/casaos-appstore-fix

`bash -c "$(wget -qLO - https://raw.githubusercontent.com/bigbeartechworld/big-bear-scripts/master/casaos-appstore-fix/run.sh)"`

but still not working.

Here's the version of Ubuntu I'm running:
```
riccardobellitto@sector5:~$ neofetch
            .-/+oossssoo+/-.               riccardobellitto@sector5
        `:+ssssssssssssssssss+:`           ------------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 23.10 aarch64
    .ossssssssssssssssssdMMMNysssso.       Host: Raspberry Pi 5 Model B Rev 1.0
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 6.5.0-1009-raspi
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 38 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 798 (dpkg), 4 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.2.15
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/0
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: BCM2835 (4) @ 2.400GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Memory: 781MiB / 7943MiB
+sssshhhyNMMNyssssssssssssyNMMMysssssss+
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```

**Comment by dragonfire1119** [comment] 2024-01-26 23:43
@riccardobellitto Do you still have the main app store installed after running the script:

```
casaos-cli app-management list app-stores
```

**Comment by dragonfire1119** [comment] 2024-01-27 00:46
I made a script to fix this: https://community.bigbeartechworld.com/t/fix-the-casaos-app-store-not-loading/593?u=dragonfire1119

**Comment by godfodder0901** [comment] 2024-01-27 01:05
> I made a script to fix this: https://community.bigbeartechworld.com/t/fix-the-casaos-app-store-not-loading/593?u=dragonfire1119

This doesn't 'fix' anything but replace the default app store.  Other app stores are still broken.

**Comment by dragonfire1119** [comment] 2024-01-27 02:06
The main App Store is the one that is broken. Other 3rparty App Store owners would need to fix their App Store if something is wrong.

**Comment by godfodder0901** [comment] 2024-01-27 20:58
> The main App Store is the one that is broken. Other 3rparty App Store owners would need to fix their App Store if something is wrong.
> 
> If you're talking about the edge app store it's a mirror of the main app store.

Bottom line, a change in CasaOS broke ALL app stores.  This is a CasaOS problem.  There is currently only a 'fix' for the official app store in the form of a different URL for the store.

**Comment by dragonfire1119** [comment] 2024-01-27 21:01
> > The main App Store is the one that is broken. Other 3rparty App Store owners would need to fix their App Store if something is wrong.
> > If you're talking about the edge app store it's a mirror of the main app store.
> 
> Bottom line, a change in CasaOS broke ALL app stores. This is a CasaOS problem. There is currently only a 'fix' for the official app store in the form of a different URL for the store.

I only see an issue with the main app store, not any third-party app store. BigBearCasaOS works just fine. It also looks like they removed the Unifi Network Application, so that should of fixed the main app store. It has at least been on my setup.

https://github.com/bigbeartechworld/big-bear-casaos

**Comment by godfodder0901** [comment] 2024-01-27 21:03
> > > The main App Store is the one that is broken. Other 3rparty App Store owners would need to fix their App Store if something is wrong.
> > > If you're talking about the edge app store it's a mirror of the main app store.
> > 
> > 
> > Bottom line, a change in CasaOS broke ALL app stores. This is a CasaOS problem. There is currently only a 'fix' for the official app store in the form of a different URL for the store.
> 
> I only see an issue with the main app store, not any third-party app store. BigBearCasaOS works just fine. It also looks like they removed the Unifi Network Application, so that should of fixed the main app store. It has at least been on my setup.
> 
> https://github.com/bigbeartechworld/big-bear-casaos

Did they fix the Edge store?  Was still broken 3 minutes ago, unless there is a new URL for that as well.

**Comment by dragonfire1119** [comment] 2024-01-27 21:06
> > > > The main App Store is the one that is broken. Other 3rparty App Store owners would need to fix their App Store if something is wrong.
> > > > If you're talking about the edge app store it's a mirror of the main app store.
> > > 
> > > 
> > > Bottom line, a change in CasaOS broke ALL app stores. This is a CasaOS problem. There is currently only a 'fix' for the official app store in the form of a different URL for the store.
> > 
> > 
> > I only see an issue with the main app store, not any third-party app store. BigBearCasaOS works just fine. It also looks like they removed the Unifi Network Application, so that should of fixed the main app store. It has at least been on my setup.
> > https://github.com/bigbeartechworld/big-bear-casaos
> 
> Did they fix the Edge store? Was still broken 3 minutes ago, unless there is a new URL for that as well.

The Edge App Store is a mirror of the main app store. It's only updated so often though:

Here is a URL to fix the edge store:
```
https://github.com/WisdomSky/CasaOS-AppStore-Edge/archive/9d5e38f670d0bddb37993276a49960842ef0ddb4.zip
```

**Comment by CorrectRoadH** [comment] 2024-01-30 07:34
dup of #1662

Thank your for your feedback🙏. The issue have fixed. the Bug is caused by the robustness of CasaOS not strong.🥲We already have a lot of moves to improve the robustness now.🥺

https://github.com/IceWhaleTech/CasaOS-AppStore/pull/414
https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/154
https://github.com/IceWhaleTech/CasaOS-UI/commit/7d257eabe5bf8f4011b436761a376458c0a50f3e

**Closed by CorrectRoadH** 2024-01-30 07:34 UTC
Labels: bug

**Comment by pachanor** [comment] 2025-08-21 22:30
Hola como soluciono este problema compre un zimablade recientemente, por favor si me pueden ayudar, gracias
