### ISSUE TITLE
[Bug] SAMBA share, no files in the folders

### ISSUE THREAD

**Issue by zarevskaya** [IceWhaleTech/CasaOS#458] opened 2022-08-16 21:24 UTC
### What happened?

Hey,

I don't see folders or files in shared folders. I'm connected with a local account.

### Screenshots

![Capture d’écran de 2022-08-16 23-21-42](https://user-images.githubusercontent.com/60230221/184987806-82343bc3-db08-4385-ae85-055983a3f60a.png)
![Capture d’écran de 2022-08-16 23-21-57](https://user-images.githubusercontent.com/60230221/184987812-5563421c-2941-4536-a9e7-70ed89167907.png)

**Comment by Hedius** [comment] 2022-08-16 21:50
I can reproduce this.

When i create new files then they are saved on the SMB share.

After rebooting / remounting i can  no longer see them in casaos.

**Comment by AuthorShin** [comment] 2022-08-16 23:31
Same here as connecting to a SMB share only result in showing the parent folder of that share (No sub folder nor files).

**Comment by LinkLeong** [comment] 2022-08-17 09:17
Fixed, the mount was not successful after reboot. Now it can be mounted normally after adding the delay.

**Comment by AuthorShin** [comment] 2022-08-18 10:49
It's still the same even with alpha.2 (John mentioned this as fixed in changelogs of alpha.2), so I'm reopening this.

**Comment by JohnGuan** [comment] 2022-08-24 03:37
> It's still the same even with alpha.2 (John mentioned this as fixed in changelogs of alpha.2), so I'm reopening this.

@LinkLeong Is it fixed in alpha.2 ?

**Comment by LinkLeong** [comment] 2022-08-24 08:45
> It's still the same even with alpha.2 (John mentioned this as fixed in changelogs of alpha.2), so I'm reopening this.

Mount a samba first, then reboot? I need steps

**Comment by AuthorShin** [comment] 2022-09-08 15:16
@ETWang1991 Since you took over #462 , can you take a look at this too?

**Comment by LinkLeong** [comment] 2022-10-24 10:29
This is the problem of omv's user and user group settings, please share according to omv's official documentation.

**Closed by LinkLeong** 2022-10-24 10:29 UTC
Labels: bug, P1

**Comment by sacredx72** [comment] 2023-03-13 12:51
I ran into the same problem as mentioned in the first post. I'm trying to samba to a Seagate Center or synology NAS network drive with the correct username and password. Authorization is successful, I can see the structure of the root drive, but all folders and subfolders are empty. Although there is information on the disks.

**Comment by DaanSchoukens** [comment] 2023-09-08 09:29
I'm having the same issue after updating to 0.4.4.2, reboot doesn't help

**Comment by vikramsoni2** [comment] 2023-10-04 20:25
> This is the problem of omv's user and user group settings, please share according to omv's official documentation.

not the omv issue. I tried adding my smb shares from debian server, and also from my windows server. same issue. the folders are empty.

**Comment by LinkLeong** [comment] 2023-10-07 02:49
> > This is the problem of omv's user and user group settings, please share according to omv's official documentation.这是omv的用户和用户组设置的问题，请根据omv官方文档分享。
> 
> not the omv issue. I tried adding my smb shares from debian server, and also from my windows server. same issue. the folders are empty.不是omv问题。我尝试从 debian 服务器以及 Windows 服务器添加我的 smb 共享。同样的问题。文件夹是空的。

With me my query is not compatible with the version of the problem caused, we are compatible with smb2-3, you check the other end of the version is not smb1, or smb1, the way to mount.

**Comment by Nuffern** [comment] 2024-02-26 00:42
I have the same problem as OP. I mounted the my Synology NAS in the Files app, and I can see the folders - but they are all empty.

Have a Synology DS920+ with DSM 7.2.1-69057 Update 3. CasaOS (0.4.6) is installed on a Proxmox LXC. Created a specific user in DSM with only access to SMB and the shared folders. Default settings for SMB (Max SMB3, Min SMB2).

**Comment by RemcoHekker** [comment] 2024-02-27 16:52
> I have the same problem as OP. I mounted my Synology NAS in the Files app, and I can see the folders - but they are all empty.
> 
> Have a Synology DS920+ with DSM 7.2.1-69057 Update 3. CasaOS (0.4.6) is installed on a Proxmox LXC. Created a specific user in DSM with only access to SMB and the shared folders. Default settings for SMB (Max SMB3, Min SMB2).

Same issue but with Synology D1019+ DSM 7.1.1-42962 update 2 
CasaOS (0.4.6) is installed on a Proxmox LXC

**Comment by oliversaal** [comment] 2024-06-21 03:05
Repro'ed this on CasaOS v.0.4.9 as well hosted as a Proxmox LXC. SMB shares are visible from other client computer (MacOS and Windows) but CasaOS only shows the top-level folders with no subfolder or file/s content. I "mounted" the SMB share using the Files app and it shows the network/host listed even after reboot with the /mnt/<host>/<-topfolder>/* is always empty.

**Comment by oliversaal** [comment] 2024-06-21 04:25
If you're running CasaOS on an Proxmox LXC container, this reddit thread might help: https://www.reddit.com/r/CasaOS/comments/16bltbw/casaos_blank_network_share_mount_through_gui/
