### ISSUE TITLE
[Bug] Environment Variables changes are not saving

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#510] opened 2022-09-04 05:49 UTC
Install any app with CasaOS (even from App Store) and then after the installation process is over open it's Setting and change one/some of the Environment Variables and then Save it, open the app's Setting again and you will see that the Environment Variables are still the same as before (unedited).

**Comment by bluehysteric** [comment] 2022-09-04 09:40
I have also encountered this problem, I think this built-in template caused, for example, a port default is TCP, change to TCP + UDP, after restart is still TCP

**Comment by AuthorShin** [comment] 2022-09-05 02:21
Yeah I had problems with custom networks in a way that CasaOS was keep resetting them to default bridge.

**Comment by Snake14777** [comment] 2022-09-05 14:22
I'm having the same problem

**Comment by Spix91** [comment] 2022-09-05 16:00
Can confirm that I have the same issue

**Comment by LinkLeong** [comment] 2022-09-06 03:58
Sorry for the bug caused by the import function, it has been fixed in 0.3.6 and will be released in the near future.

**Comment by LinkLeong** [comment] 2022-09-14 06:48
This issue has been fixed in 0.3.6, I will close the issue, if you have questions, you can ask again.

**Closed by LinkLeong** 2022-09-14 06:48 UTC
Labels: bug

**Comment by fauzanocthory** [comment] 2025-02-14 04:06
Its still, my env variable doesnt change
