### ISSUE TITLE
[Bug] Casaos-gateway command using 100% cpu constantly

### ISSUE THREAD

**Issue by jorgef72** [IceWhaleTech/CasaOS#654] opened 2022-11-03 09:17 UTC
I log into CasaOS and the CPU is always nearly at 100%

**Describe the bug**
I log into CasaOS and the CPU is always nearly at 100%

**To Reproduce**
1. Log into CasaOS 
2.  Check CPU utilization which is always at 100%
3. Did a TOP command run via SSH to CasaOS to verify.
4.  Verified - PID 580, User root, cammand casaos-gateway utilizaing 100% of CPU

**Expected behavior**
If I reboot the Raspberry its stops but the next day it starts again and just goes on for hours. Not sure how long it takes as I reboot the Pi to get things back to normal. Expected behaviour is not this to happen. Using latest version o CasaOS v0.3.7. On version v0.3.6 this did not happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Raspbian GNU/Linux 11 (bullseye)
 - Browser [chrome]
 - Version [11]

**Additional context**
Running  CASAOS on raspberry Pi 4 with 4 GB RAM

**Comment by CosmoFox** [comment] 2022-11-03 11:36
Same problem, overheating CPU
![2022-11-03_14-34-53](https://user-images.githubusercontent.com/9054349/199710883-1551f1ca-9bda-4577-a922-496970bc4670.png)

**Comment by bhanuprakash9980** [comment] 2022-11-04 06:08
Same problem, because of this eventually lighttpd goes to 100% usage and all the apps that use lightttpd gets stuck

**Comment by tigerinus** [comment] 2022-11-04 11:25
@CosmoFox @bhanuprakash9980 r u also using Raspberry Pi?

**Comment by tigerinus** [comment] 2022-11-04 11:31
@jorgef72 can u run

```
sudo journalctl -xef -u casaos-gateway
```

And share the logs?

**Comment by CosmoFox** [comment] 2022-11-04 12:39
> @CosmoFox @bhanuprakash9980 r u also using Raspberry Pi?

No, its mini PC with Intel CPU

**Comment by tigerinus** [comment] 2022-11-04 12:48
> > @CosmoFox @bhanuprakash9980 r u also using Raspberry Pi?
> 
> No, its mini PC with Intel CPU

```bash
sudo journalctl -xef -u casaos-gateway
```

Can u run this and share the results?

**Comment by bhanuprakash9980** [comment] 2022-11-04 18:48
> @CosmoFox @bhanuprakash9980 r u also using Raspberry Pi?

Yes, I am using raspberry pi

**Comment by bhanuprakash9980** [comment] 2022-11-04 18:55
> @jorgef72 can u run
> 
> ```
> sudo journalctl -xef -u casaos-gateway
> ```
> 
> And share the logs?

[tmp.txt](https://github.com/IceWhaleTech/CasaOS/files/9941282/tmp.txt)

**Comment by bhanuprakash9980** [comment] 2022-11-05 07:23
Hi so i uninstalled casaos reinstalled lighttpd and then installed casaos again yesterday it's been almost 12 hrs and this issue is not seen. Not sure what changed but i do not have this rn.

**Comment by tigerinus** [comment] 2022-11-05 11:35
> Hi so i uninstalled casaos reinstalled lighttpd and then installed casaos again yesterday it's been almost 12 hrs and this issue is not seen. Not sure what changed but i do not have this rn.

I am not able to reproduce this issue at all. The gateway is not changed during 0.3.7. It is supposed to be the same version as 0.3.6.

How do u install lighttpd?

**Comment by bhanuprakash9980** [comment] 2022-11-05 11:37
https://pimylifeup.com/raspberry-pi-lighttpd//
Used this

**Comment by tigerinus** [comment] 2022-11-05 11:52
> https://pimylifeup.com/raspberry-pi-lighttpd// Used this

@jorgef72 @CosmoFox r u using similar set-up?

I couldn't reproduce this issue at all.

**Comment by jorgef72** [comment] 2022-11-05 15:58
There has been a CasaOS update 0.3.7.1 which for me seems to have fixed the issue. I have not had it since the update this update.

**Comment by tigerinus** [comment] 2022-11-05 21:26
Great. v0.3.7.1 has fixed a very bad goroutine leak.

I am closing this issue.

If @CosmoFox still experience the issue even after upgrading to 0.3.7.1 please reopen.

**Closed by tigerinus** 2022-11-05 21:26 UTC
Labels: bug, question

**Comment by CosmoFox** [comment] 2022-11-07 02:14
> Great. v0.3.7.1 has fixed a very bad goroutine leak.
> 
> I am closing this issue.
> 
> If @CosmoFox still experience the issue even after upgrading to 0.3.7.1 please reopen.

Sorry for long reply, was far away from pc. After reboot my miniPC - problem not detected anymore.
journal from 0.3.7
[037.txt](https://github.com/IceWhaleTech/CasaOS/files/9947604/037.txt)
installed update 0.3.7.1
[0371.txt](https://github.com/IceWhaleTech/CasaOS/files/9947607/0371.txt)

Problem not detected. Keep watching..
