### ISSUE TITLE
[Feedback]Docker CLI add of container will not let you use same port for diff type

### ISSUE THREAD

**Issue by gamkiller77** [IceWhaleTech/CasaOS#957] opened 2023-03-15 21:50 UTC
### Description

When you go to add a custom app and give it ports like 53 TCP and 53 UDP, the UI reports a duplicate port being used.  I know this is a UI check to make sure the same port is not being used on the same protocol is a better check.  Can this be updated?

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.2
	 - Disk Total: 27712 
	 - Disk Used: 17741 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux mgmt1 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux]
	 - Remote Version: 0.4.2
	 - Browser: Chrome 
	 - Version: 110.0.0.0

**Comment by tigerinus** [comment] 2023-03-16 01:10
I tried changing TCP to UDP (or the other way) on my app it doesn't report anything like dup ports.

@gamkiller77 - what are the steps to reproduce this issue? can you provide a screenshot?

**Comment by gamkiller77** [comment] 2023-03-16 20:28
So I added the app via the custom app and then went to the DockerCLI tab.
`
docker run -p 8090:8090 -p 53:53/tcp -p 53:53/udp -v /dns_mysql:/etc/bind -v /dns_mysql:/var/lib/mysql conceptant/bind9-namedmanager
`
![Screenshot 2023-03-16 at 1 18 35 PM](https://user-images.githubusercontent.com/4006474/225743840-ca843552-4fe2-4aa3-8736-58fdf4044a53.png)
After clicking the install and I get this error.

![Screenshot 2023-03-16 at 1 21 26 PM](https://user-images.githubusercontent.com/4006474/225744997-7b0a0f8a-3d7d-41fe-8b75-073f8656c8d1.png)

**Comment by zhanghengxin** [comment] 2023-05-22 10:39
Version 0.4.4 fully supports Compose, but in this case, port 53 must not be in use by another process.

**Comment by tigerinus** [comment] 2023-06-26 22:25
closing since this is done in v0.4.4

**Closed by tigerinus** 2023-06-26 22:25 UTC
Labels: feedback
