### ISSUE TITLE
[Issue] Applications cannot be deleted

### ISSUE THREAD

**Issue by marawan6569** [IceWhaleTech/CasaOS#781] opened 2022-12-25 11:57 UTC
### Description

After the last update i can't delete any app i installed

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.0
	 - Disk Total: 22257 
	 - Disk Used: 7286 
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:5887M Core:4 Linux homeserver 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64 GNU/Linux]
	 - Remote Version: 0.4.0
	 - Browser: Chrome 
	 - Version: 108.0.0.0

**Comment by raller1028** [comment] 2022-12-26 10:02
Can you provide more information about the error, or how to reproduce the problem?

**Comment by marawan6569** [comment] 2022-12-27 07:54
- lets say  i want to uninstall OpenSpeedTest:
![image](https://user-images.githubusercontent.com/38116633/209631235-ac3b8964-98e1-45c9-87f8-58b0ec497367.png)
- When I click on uninstall:
![image](https://user-images.githubusercontent.com/38116633/209631504-2430e8f8-9da3-4108-93a0-65c2e3c08da8.png)
- i see this message:
![image](https://user-images.githubusercontent.com/38116633/209631683-4946343b-70a8-4874-9982-1841b2a59373.png)
- when clicking uninstall again the app keeps loading and nothing happens:
![image](https://user-images.githubusercontent.com/38116633/209631950-5af93d4e-443b-4bb5-ac2b-136e731dd2ff.png)

**Comment by zhanghengxin** [comment] 2022-12-28 06:22
@marawan6569 
 Can you tell me about your language of casaos

**Comment by raller1028** [comment] 2022-12-28 06:52
It should be the problem of missing translation files, can you upgrade again? Upgrade command: curl -fsSL https://get.casaos.io/update | sudo bash

**Comment by marawan6569** [comment] 2022-12-29 07:19
I upgraded again and the same error is still happening

**Comment by zhanghengxin** [comment] 2023-01-05 16:28
because something wrong here. 
![image](https://user-images.githubusercontent.com/24197448/210828566-26034d1a-e49c-4581-b732-d2ff2f57ee2e.png)

when it can display the condition box correctly, it can delete the application correctly.

the reason for it's incorrect display may be adsence of translation.

In addition, my policy is fault-tolerant data processing. These issues will be addressed in 0.41-alpha.

**Comment by raller1028** [comment] 2023-01-10 06:33
@marawan6569 Can you update v0.4.1 to check if the delete problem still exists?
Update command:    curl -fsSL https://get.casaos.io/update/v0.4.1-alpha1 | bash

**Comment by marawan6569** [comment] 2023-01-24 11:36
@raller1028 
I tried to update but it always fails

So I formatted the server and reinstalled it (debian 11) twice to get rid of this problem.
Now I can delete applications but these texts are still not readable:
![image](https://user-images.githubusercontent.com/38116633/214281064-e608e35b-2df6-4643-868b-06184e0d81da.png)
![image](https://user-images.githubusercontent.com/38116633/214281185-11a504e1-745d-40ad-83dd-76168ba51b5a.png)


Sometimes the installation of apps fails with
out any error message
Sometimes I feel that the server is running slow and does not take advantage of the capabilities of the device

**Comment by raller1028** [comment] 2023-01-31 09:23
@marawan6569 Can you update to v0.4.1 successfully now? And can you send device information

**Comment by raller1028** [comment] 2023-01-31 09:30
And you can try to change languageIs the language you are using English? If not, can you try changing the language to English to check if the problem still exists?

**Comment by marawan6569** [comment] 2023-01-31 13:48
@raller1028 
yes, i updated to v0.4.1
the language i am using is English.
i tried to change to another language and change to English again and it works now.
thank you for your help.

![image](https://user-images.githubusercontent.com/38116633/215777678-791cedea-f7bb-47cc-ad8d-33ca1dc27a69.png)
![image](https://user-images.githubusercontent.com/38116633/215777806-fbe82d31-a2bf-488d-8089-31962abf09e4.png)

**Comment by zhanghengxin** [comment] 2023-02-01 03:16
You can contribute translation [here](https://crowdin.com/project/casaos)

**Comment by zhanghengxin** [comment] 2023-02-01 03:27
I found the cause, I will fix it in 0.4.2. Thank you!

**Closed** 2023-02-01 16:10 UTC
Labels: question
