### ISSUE TITLE
APP Store is not loading

### ISSUE THREAD

**Issue by sammzinc** [IceWhaleTech/CasaOS#269] opened 2022-06-09 11:00 UTC
**Describe the bug**

Hello, 
I am unable to open app store, already ran following command, systemctl restart casaos.service. casaos is install on a zimaboard.
Thanks

**System infomation**

	 - OS: linux
	 - CasaOS Version: 0.3.1.1
	 - Disk Total: 27712 
	 - Disk Used: 12291 
	 - Sync State: Sync img: true
	linuxserver/syncthing:latest,
	Sync Key length: 32
	 - System Info: [Debian GNU/Linux 11   \l Bit:64 Mem:7801M Core:4 Linux CasaOS 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux]
	 - Browser: Edge 
	 - Version: 102.0.1245.30

**Comment by AuthorShin** [comment] 2022-06-09 18:05
Hello
It might be because of that they use `amazonaws.com` and many ISP in world issuing connectivity problems to it.

**Comment by moravel** [comment] 2022-06-10 08:22
May be like here : https://github.com/IceWhaleTech/CasaOS/issues/254

**Comment by JohnGuan** [comment] 2022-06-13 11:13
We are trying to solve this problem

**Comment by AlexFigas** [comment] 2022-06-16 20:47
```
> 

pi@raspberrypi:~ $ ping amazonaws.com
PING amazonaws.com (72.21.206.80) 56(84) bytes of data.
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=1 ttl=229 time=91.6 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=2 ttl=229 time=90.7 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=3 ttl=229 time=90.8 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=4 ttl=229 time=91.3 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=5 ttl=229 time=90.9 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=6 ttl=229 time=90.8 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=7 ttl=229 time=91.1 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=8 ttl=229 time=91.0 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=9 ttl=229 time=95.1 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=10 ttl=229 time=90.9 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=11 ttl=229 time=90.6 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=12 ttl=229 time=91.1 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=13 ttl=229 time=90.7 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=14 ttl=229 time=90.8 ms
64 bytes from amazonaws.com (72.21.206.80): icmp_seq=15 ttl=229 time=90.6 ms
^C
--- amazonaws.com ping statistics ---
15 packets transmitted, 15 received, 0% packet loss, time 14022ms
rtt min/avg/max/mdev = 90.554/91.192/95.062/1.065 ms
```

I don't think so, at least not on my side.

**Comment by mvmelo** [comment] 2022-06-18 12:27
Hi,

I had the same problem using Raspberry Pi 4. I tried different systems as the base Operating Systems (Raspbian 32,  Rapbian 64 bit and Ubuntu 64) and confirmed app store is not loading on all this three OSs.

If there's anything I can help (screenshots or outputs), I can post here.

Thank you for your work with CasaOS!

**Comment by AlexFigas** [comment] 2022-06-18 13:41
> Hi,
> 
> I had the same problem using Raspberry Pi 4. I tried different systems as the base Operating Systems (Raspbian 32, Rapbian 64 bit and Ubuntu 64) and confirmed app store is not loading on all this three OSs.
> 
> If there's anything I can help (screenshots or outputs), I can post here.
> 
> Thank you for your work with CasaOS!

It is fixed now. It was an API issue. Reinstall CasaOS if it was your first install. If not, hop into discord and let us know the issue.

**Comment by Felix-Pedro** [comment] 2022-06-21 00:24
I'm having the same issue with a fresh install made just a few minutes ago, did the api had problems again?

**Comment by JohnGuan** [comment] 2022-06-21 01:12
New feedback for the same problem is dated 17, 18, 21

**Comment by tigerinus** [comment] 2022-06-21 03:06
There has been few requirements created related to App Store within the team, which should dramatically improve the reliability of app store loading.

**Comment by Felix-Pedro** [comment] 2022-06-23 15:10
Hey, I've managed to solve on my system and might help you out, at least on cento os there was a dependency conflict with docker and podman, so I docker wasn't able to start, after removing podman-docker and reinstalling docker-ce and starting the service appstore loaded normally

**Comment by tigerinus** [comment] 2022-07-05 01:05
We've fixed couple of issues in load balance in front of app store service. Closing this issue for now, but definitely let us know if this is still happening.

**Closed by tigerinus** 2022-07-05 01:05 UTC
Labels: bug, area:appstore
